### ISSUE TITLE
Prepare for WP Plugin directory submission

### ISSUE THREAD

**Issue by jplhomer** [jplhomer/taghound-media-tagger#12]
I have no idea how to go about this.

Would be nice to use somebody's automated script to sync the repo to SVN and minify, etc.
## Todo
- [x] Finalize name
- [x] Write out descriptions
- [x] Fill out Installation instructions on Readme.txt
- [x] Take Screenshots
- [ ] Create logo and banners for WP repo
- [x] Create page on jplhomer.org and add documention
- [x] Submit to WP repository
- [x] Clone down SVN repo and connect it with Git

**Comment by kjbrum** [comment]
This might be useful? https://github.com/kasparsd/wp-deploy

**Comment by jplhomer** [comment]
@kjbrum 👍 that looks awesome. Kind of a bummer you still have to use SVN to get these puppies out there.

**Comment by kjbrum** [comment]
@jplhomer Super bummer, makes it unnecessarily difficult.
